version: "3.8"
services:
  postgres:
    image: postgres
    ports:
      - 5432:5432
    volumes:
      - ./db/postgres:/docker-entrypoint-initdb.d/
    environment:
      POSTGRES_USER: p-wi-user
      POSTGRES_PASSWORD: p-wi-password
      POSTGRES_DB: p-wi
  mongo:
    image: mongo
    ports:
      - 27017:27017
    volumes:
      - ./db/mongo:/docker-entrypoint-initdb.d/
    environment:
      MONGO_INITDB_ROOT_USERNAME: m-wi-user
      MONGO_INITDB_ROOT_PASSWORD: m-wi-password
      MONGO_INITDB_DATABASE: m-wi
